services:
  - type: web
    name: educar-ia
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GROQ_API_KEY
        scope: env
        value: ""
